
UI_INFO = "UI_INFO"

UI_INFO_CONNECTED = [ UI_INFO, "CONNECTED" ]
UI_INFO_CONNECTING = [ UI_INFO, "CONNECTING" ]

WM_IR = "WM_IR"    # self.ev.send( WM_IR, [pdots, dots_on] )


EV_SHUTDOWN = "EV_SHUTDOWN" #Time to quit!

WMDPOWER = "WMDPOWER"
